apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "httpserver.fullname" . }}
  labels:
    app: {{ include "httpserver.name" . }}
    chart: {{ include "httpserver.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Values.version | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "httpserver.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "httpserver.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: httpserver-conf
          persistentVolumeClaim:
            claim: httpserver-conf
        - name: httpserver-views
          persistentVolumeClaim:
            claim: httpserver-views
        - name: httpserver-static
          persistentVolumeClaim:
            claim: httpserver-static
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              cpu: "100m"
          volumeMounts:
            - mountPath: "/go/src/conf"
              name: httpserver-conf
            - mountPath: "/go/src/views"
              name: httpserver-views
            - mountPath: "/go/src/static"
              name: httpserver-static
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
