pipeline:
    # build docker image
    # send image to dockerhub
    # apply update to k8s cluster
    docker:
        image: plugins/docker
        prefix: DOCKER
        secrets: [ docker_username, docker_password ]
        repo: codedepot/httpserver
        tags: 
            - latest
        when: 
            branch: [master]
    helm_deploy:
        image: codedepot/httpserver
        skip_tls_verify: true
        chart: ./charts/httpserver
        release: ${DRONE_BRANCH}
        prefix: HELM
        secrets: [helm_api_server, helm_kubernetes_token]
        update_dependencies: true
        when:
            branch: [master]
        dry-run: true 